### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by babaloveyou** [hakluke/hakcheckurl#10]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x63f123]

goroutine 938 [running]:
main.main.func1(0xc000016350, 0xc0000241e0, 0xc0000aebd0, 0xc0005cc8e0, 0x1d)
        /root/go/pkg/mod/github.com/hakluke/hakcheckurl@v0.0.0-20200115001753-831a993f088d/main.go:51 +0x113
created by main.main
        /root/go/pkg/mod/github.com/hakluke/hakcheckurl@v0.0.0-20200115001753-831a993f088d/main.go:46 +0x2de

**Comment by hakluke** [comment]
Hey @babaloveyou, what version of go are you using?
